application: pad-matt-diesel
version: 1
runtime: python27
api_version: 1
threadsafe: no

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

handlers:
- url: /static
  static_dir: static

- url: /css
  static_dir: static/css

- url: /img
  static_dir: static/img

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /.*
  script: main.application
